harnessApiVersion: '1.0'
type: BUILD
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - YqN5jEuwQLeE7FSQitFG9A
phases:
- daemonSet: false
  name: Phase 1
  phaseSteps:
  - type: PREPARE_STEPS
    name: Prepare Steps
    stepsInParallel: false
  - type: COLLECT_ARTIFACT
    name: Collect Artifact
    steps:
    - type: SHELL_SCRIPT
      name: Shell Script_2
      properties:
        commandPath: null
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        outputVars: ''
        publishAsVar: false
        scriptString: |-
          echo "Execute script"
          ls
          whoami
          ls ./ConfigMyApp
          echo "Execute script..."
          cat ./ConfigMyApp/config.json
          ./ConfigMyApp/configMyApp.sh TPV no no dev
          echo "Done."
        scriptType: BASH
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        tags: null
        templateExpressions: null
        templateVariables: ''
        timeoutMillis: 60000
    - type: SHELL_SCRIPT
      name: My Shell Script
      properties:
        commandPath: null
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        outputVars: ''
        publishAsVar: false
        scriptString: "#!/bin/bash\necho \"Hello world!\"\napt-get -y install git\n\
          apt-get -y install jq\napt-get -y install -f \ngit --version\nuname -m\n\
          echo \"remote\"\ngit config remote.origin.url https://github.com/Appdynamics/ConfigMyApp.git\n\
          echo \"Cloning repo...\" \ngit config --global credential.helper cache\n\
          git clone https://AlexJov:fa64a47df9c0fc8ae6bbff0c77d7ffea14737e24@github.com/Appdynamics/ConfigMyApp.git\
          \ -b features/jenkins_pipeline --single-branch ConfigMyApp\necho \"Cloned\""
        scriptType: BASH
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        tags: null
        templateExpressions: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeoutMillis: 180000
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  statefulSet: false
templatized: false
userVariables:
- type: TEXT
  allowedValues: dev,qa,prod,test
  fixed: true
  mandatory: true
  name: APP_ENVIRONMENT
  value: dev
