apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    run: ConfigMyApp
  name: ConfigMyApp
spec:
  replicas: 1
  selector:
    run: ConfigMyApp
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ConfigMyApp
    spec:
      containers:
      - image: iogbole/configmyapp:latest
        name: ConfigMyApp
        resources: {}
        envFrom:
          - secretRef:
             name: dev-secret
status:
  replicas: 0
